services:
  - type: web
    name: login-system-node
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://albertsleyther:09NbqGe9gecOLTBy@ecommerce.6lrddnh.mongodb.net/?retryWrites=true&w=majority
      - key: BASE_URL
        value: https://login-system-nodejs.onrender.com
      - key: PORT
        value: 5000
      - key: SESSION_SECRET
        value: un_secreto_complejo_aqui_123